plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.yx.tools'
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        applicationId "com.yx.tools"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "3.0.0"
    }

    signingConfigs {
        release {
            storeFile rootProject.file('release.keystore')
            storePassword KEYSTORE_PASS
            keyAlias 'yx'
            keyPassword KEYSTORE_PASS
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation files('libs/yx.aar')
}
